version: "3.8"
#Comentario de prueba para comprobar que el despliegue actualiza el yml correctamente
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile.phpapache
    container_name: apache1
    depends_on:
      - "mysql"
    volumes:
      - "./www:/var/www/html/"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    networks:
      dmz:
        ipv4_address: 192.168.1.11

  php-apache2:
    build:
      context: .
      dockerfile: Dockerfile.phpapache
    container_name: apache2
    depends_on:
      - "mysql"
    volumes:
      - "./www:/var/www/html/"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    networks:
      dmz:
        ipv4_address: 192.168.1.12

  php-apache3:
    build:
      context: .
      dockerfile: Dockerfile.phpapache
    container_name: apache3
    depends_on:
      - "mysql"
    volumes:
      - "./www:/var/www/html/"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    networks:
      dmz:
        ipv4_address: 192.168.1.13

  mysql:
    image: "mysql:latest"
    container_name: mysql
    volumes:
      - "./bdd:/var/lib/mysql"
    command: 
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "proyecto"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    networks:
      dmz:
        ipv4_address: 192.168.1.21

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: phpmyadmin
    depends_on:
      - "mysql"
    links:
      - "mysql"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
      UPLOAD_LIMIT: "256M"
    networks:
      dmz:
        ipv4_address: 192.168.1.22

  balanceador:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: balanceador
    networks:
      dmz:
        ipv4_address: 192.168.1.10
    ports:
      - "8081:80"
    stdin_open: true
    tty: true
    volumes:
      - "./nginx:/etc/nginx"


networks:
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
